version: '2'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Test_2311:/Test_2311
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
#    environment:
#      - DB_HOST=db
#      - DB_NAME=app
#      - DB_USER=postgres
#      - DB_PASS=supersecretpassword
#      - MAIL_USER=mail_user
#      - MAIL_PASSWORD=mail_password
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.dev
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A Test_2311 worker -l info
    volumes:
      - ./Test_2311:/Test_2311
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata:
#    ports:
#      - "5432:5432"
